version: '2'
services:
  registry:
    image: registry:2
    restart: always
    depends_on:
      - config
      - security
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry-data:/var/lib/registry
      - registry-config:/etc/docker/registry
    volumes_from:
      - security

  config:
    image: registry:2
    entrypoint: ''
    volumes:
      - registry-config:/config
    command: >
      /bin/sh -c '
      config_path=/config/config.yml;

      if [ ! -e $$config_path ]; then
          cp /etc/docker/registry/config.yml $$config_path;
      fi;

      grep -q delete $$config_path || sed -i -e "s/^storage:/storage:\n  delete:\n    enabled: true/" $$config_path

      #echo "abusing strings is fun!"
      '

  security:
    image: roberto/private-registry
    environment:
      - REGISTRY_DOMAIN_NAME
    volumes:
      - registry-auth:/auth
      - registry-certs:/certs


volumes:
  registry-auth:
    driver: local

  registry-certs:
    driver: local

  registry-config:
    driver: local

  registry-data:
    driver: local
