version: '3.4'
services:
  app:
    image: ${DOCKER_IMAGE}
    ports:
      - ${SERVICE_PORT}:5000
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE
      - REGISTRY_HTTP_TLS_KEY
      - REGISTRY_AUTH
      - REGISTRY_AUTH_HTPASSWD_PATH
      - REGISTRY_AUTH_HTPASSWD_REALM
      - PRIVATEREGISTRY_CONF
      - PRIVATEREGISTRY_TLS
      - PRIVATEREGISTRY_AUTH_ENTRIES
    volumes:
      - docker-registry-registry-data:/var/lib/registry
